include::shared/attributes.adoc[]

[[property-management]]
= Property Management

The following steps describe how to configure the {ProductShortName} command line tool (fhc) to enable property management.

[[property-management-requirements]]
== Requirements

Follow the instructions to link:{local-development-guide}#installing-fhc[install the RHMAP command line tool (fhc)], and make sure that it is working. 

[WARNING]
--
Altering properties might adversely affect {ProductShortName}. Do not modify properties other than the example in this guide unless you are instructed to do so by Red Hat support. 
--

[[managing-properties]]
== Managing Properties

1. To manage properties you must first set the configuration to target
the cluster using the following command, where `<cluster-url>`
is the domain name of the target:
+
[source,bash]
----
fhc target <cluster-url>
----
+
For example, if  {ProductShortName} is running on the domain https://rhmap.example.com, the user would set the target by entering:
+
[source,bash]
----
fhc target https://rhmap.example.com
----

2. To modify the cluster properties, log in as the admin user to ensure that you have the required
permissions. Either use the `fhc login` command and respond to the prompts for a username and password or use the `fhc login  <username> <password>` command.
+
NOTE: If you using a self-managed Core the
credentials for the admin user are stored as environment variables, `${FH_ADMIN_USER_NAME}` and
`${FH_ADMIN_USER_PASSWORD}`, in the Millicore pod.

3. Use the `fhc clusterprops` command to modify properties. The following CRUDL commands are available:
* Create: `fhc clusterprops create <property> <value>;`
* Read: `fhc clusterprops read <property>;`
* Update `fhc clusterprops update <property> <value>;`
* Delete `fhc clusterprops delete <property> <value>;`
* List `fhc clusterprops list;`

[[example-properties-modification]]
== Example Properties Modification

As an example, you might require that when a new user is created, an invitation email is sent to the user, and the user must set their password. You can use the `password.setExpiryTime` property to make sure that the email expires.

[WARNING]
--
Altering properties might adversely affect {ProductShortName}. Do not modify properties other than the example in this guide unless you are instructed to do so by Red Hat support. 
--

1. Enter the following command to view the current setting for this property:
+
[source,bash]
----
fhc clusterprops read password.setExpiryTime
----
+
The output displays in a similar format to the following:
+
[cols=",^,^",options="header",]
|==================================================
|guid |Name |Value
|none |password.setExpiryTime |720
|==================================================

2. To change the value to 500, use the update command:
+
[source,bash]
----
fhc clusterprops update password.setExpiryTime  500
----

3. Verify the setting by entering:
+
[source,bash]
----
fhc clusterprops read password.setExpiryTime
----
+
Check the output:
+
[cols=",^,^",options="header",]
|===================================================
|guid |Name |Value
|none |password.setExpiryTime|500
|===================================================
