include::shared/attributes.adoc[]

[[cordova-light]]
= Cordova Light

[IMPORTANT]
--
The use of Cordova Light for app development is deprecated in favor of standard Cordova.

You can no longer create new apps based on Cordova Light in the Studio.
You can still build existing Cordova light Apps using the Build Farm.

To continue using your apps, you can link:{MobileDeveloperGuide}#migrate-cordova-light-cordova[migrate your Cordova Light apps to standard Cordova] or link:{MobileDeveloperGuide}#migrate-cordova-light-cordova-overview[import you existing Cordova Light apps] into your project in {ProductShortName} Studio.
--

[[cordova-light-download]]
== Download

* https://github.com/feedhenry/fh-js-sdk/releases[SDK^]
* https://github.com/feedhenry-templates/helloworld-app.git[Sample App^]

[[cordova-light-get-started]]
== Get Started

The {ProductShortName} JavaScript SDK lets you use {ProductShortName} APIs in Cordova Light apps, which are Cordova apps with just the `www` directory exposed. These apps use standard web technology only -- HTML, CSS, JavaScript. There is no exposure to any native code.

Cordova Light Apps are a simple and straightforward way to learn to use the {ProductName} ({ProductShortName}), but restrict the developer to only being able to use standard link:{MobileDeveloperGuide}#using-cordova-plug-ins[Cordova plugins].

[[cordova-light-new-app]]
=== New App

Download the https://github.com/feedhenry-templates/helloworld-app.git[sample app^] to get started with a new Cordova Light App which has the {ProductShortName} SDK already included.

[[cordova-light-existing-app]]
=== Existing App

Download the SDK and save it as `feedhenry.js`.

Copy the `feedhenry.js` into your Cordova app, to the same location as your index.html file - typically in the `/www` directory.

Add the following code to your `index.html` file:

[source,html]
----
<head>
  <script src="feedhenry.js" type="text/javascript"></script>
</head>
----

[[cordova-light-setup]]
=== Setup

NOTE: The `fhconfig.json` file may already exist in the `/www` directory. In this case, it is only necessary to check the contents of this file.

Finally, you need to define properties which allow your app to communicate with {ProductShortName} servers. Create a new file in the same directory as the SDK file, called `fhconfig.json`, with the following contents, replacing the references in brackets with values from your project:

[source,javascript]
----
{
  "host": "<RHMAP Core host>",
  "projectid": "<Project ID>",
  "connectiontag": "<Connection tag>",
  "appid": "<Client App ID>",
  "appkey": "<Client App API key>"
}
----

See link:{ProductFeatures}#projects-connections[Projects - Connections] for more information on connections between Client Apps and Cloud Apps.

[[cordova-light-api-documentation]]
== API Documentation

* link:{ClientAPI}[API Docs] - documentation for all Client APIs
