include::shared/attributes.adoc[]

[[package-distribution-setup]]
= Client SDK Package Distribution Tool Setup

[[package-distribution-setup-overview]]
== Overview

This guide covers the installation procedures for package distribution and dependency management tools used to distribute {ProductShortName} Client SDKs.

* xref:install-npm[npm]
* xref:install-gradle[Gradle]
* xref:install-maven[Maven]
* xref:install-nuget[NuGet]
* xref:install-cocoapods[CocoaPods]

[[install-npm]]
== npm

npm is the package manager for distributing JavaScript code. It is used to install the {ProductShortName} JavaScript SDK for developing Cordova apps.

[[install-npm-installer]]
=== Installing Node.js and npm

You must have Node.js installed on your system to use npm.
It is recommended that you install NodeJS version 4.x or later, which includes npm version 2.x by default.

[[install-npm-package-manager]]
==== Install Node.js Using a Package Manager

To install Node.js using your system package manager, follow the instructions appropriate for your system on the link:https://nodejs.org/en/download/package-manager/[Node.js site^]

To check the version of npm you are currently using, execute the following command:

[source,bash]
--
sudo npm -v
--

[[install-npm-rhel]]
=== Installing Node.js and npm on Red Hat Enterprise Linux

To install NodeJS on systems running RHEL, you must obtain the installation files from the Red Hat Software Collections. Installing NodeJS requires a subscription to the Red Hat Subscription Manager.

To install NodeJS on RHEL, follow the link:https://developers.redhat.com/products/softwarecollections/hello-world/[guide^] on the Red Hat Developers Portal.

[[install-gradle]]
== Gradle

Gradle is a Java-based dependency management and build tool used for Android app development.
It is used to distribute and integrate the {ProductShortName} Native Android SDK with your app project.

[[install-gradle-installer]]
=== Installing and Setting Up Gradle

Gradle requires Java JDK or JRE version 7 or higher.
To check the version of Java you are currently using, execute the following command:

[source,bash]
--
java -version
--

[NOTE]
--
Gradle uses the JDK version link:https://docs.gradle.org/current/userguide/installation.html#sec:installation_environment_variables[specified^] in your `PATH` environmental variable.
You can also set the `JAVA_HOME` environmental variable to point to the installation directory of the desired JDK version.
--

It is recommended that you use Gradle version 2.4 or higher

To install Gradle, follow the link:https://docs.gradle.org/current/userguide/installation.html[installation instructions and setup instructions] on the Gradle website.

Alternatively, to install Gradle using the SDK manager tool, follow the section with instructions on link:https://gradle.org/gradle-download/[installing Gradle using SDKMAN] on the Gradle website.

[[install-maven]]
== Maven

Apache Maven is a project management and build automation tool for maintaining and distributing Java code. It is distributed under the Apache License, version 2.0. In an {ProductShortName} context, is used to distribute the {ProductShortName} Native Android SDK.

[[install-maven-installer]]

Maven 3.3 requires JDK 1.7 or later to execute.
To check the version of Java you are currently using, execute the following command:

[source,bash]
--
java -version
--

[NOTE]
--
Maven uses the JDK version link:https://maven.apache.org/install.html[specified^] in your `PATH` environmental variable.
You can also set the `JAVA_HOME` environmental variable to point to the installation directory of the desired JDK version.
--

You can link:https://maven.apache.org/download.cgi[download^] the latest version of Maven from the Maven developers' website.

See the Maven documentation for detailed instructions on how to link:https://maven.apache.org/install.html[install^] and link:http://maven.apache.org/configure.html[configure^] Maven.

[[install-nuget]]
== NuGet

NuGet is a dependency management tool for the Microsoft development platform including .NET and is used to share and distribute C# code.
It serves as the primary tool for distributing the {ProductShortName} .NET Client SDK.

[[install-nuget-installer]]
=== Install the NuGet CLI using the Installer

To install NuGet on Windows-based Systems, download and run the link:https://dist.nuget.org/index.html[NuGet Commandline installer^].

[[install-nuget-chocolatey]]
=== Install NuGet Using Chocolatey

If you are using link:https://chocolatey.org/[Chocolatey^], you can install NuGet by executing the following command on the Windows command line:

[source,bash]
--
choco install nuget.commandline
--

[[install-cocoapods]]
== CocoaPods

[NOTE]
--
CocoaPods is available only on OSX.
--

CocoaPods is a Swift And Objective-C dependency manager for link:https://developer.apple.com/download/[Xcode^] projects. It is built with Ruby, which comes pre-installed with OSX. It is used to distribute the {ProductShortName} iOS Swift and iOS Objective-C Client SDKs.

[[install-cocoapods-gem]]
=== Install CocoaPods Using RubyGems

To install CocoaPods using the RubyGems package manager, execute the following command. This requires the `sudo` command to be  link:https://support.apple.com/en-us/HT204012[enabled^] in OSX.

[source,bash]
--
sudo gem install cocoapods
--

As an optional part of the CocoaPods setup, you can store your link:http://guides.cocoapods.org/making/specs-and-specs-repo.html[Podspec^] metadata locally at `~/.cocoapods/repos`. This helps to increase the dependency resolution speed and shortens the build time for your apps. To clone the link:https://github.com/CocoaPods/Specs[spec-repo^] and create the directory, execute the following command:

[source,bash]
--
pod setup
--

[[install-cocoapods-no-root]]
=== Install CocoaPods Without Using sudo.

Alternatively, to install CocoaPods without using sudo, follow the _Sudo-less Installation_ section of the link:https://guides.cocoapods.org/using/getting-started.html#getting-started[CocoaPods Getting Started Guide^].

[[install-cocoapods-plugins]]
=== Install the Required Plugins

The {ProductShortName} iOS Objective-C and Swift SDK packages rely on the `cocoapods-packager` and `cocapods-appledoc` plugins. To install both plugins, execute the following command:

[source,bash]
--
[sudo] gem install cocoapods-packager cocoapods-appledoc
--

[[install-cocoapods-initialize]]
=== Enable CocoaPods in an Xcode Project

To enable Cocoapods Xcode app project after installation execute the following commands:

. To navigate to the folder of your Xcode project, use:
+
[source,bash]
--
cd <project_directory>
--
+
. To create a podfile (if it does not already exist) in your project folder and automatically populate it with targets specified within the project, execute the following command:
+
[source,bash]
--
pod init
--

[[install-cocoapods-dependencies]]
=== Install Dependencies Using CocoaPods

To install the dependencies defined in the podfile of Xcode project using CocoaPods, execute the following command:

[source,bash]
--
pod install
--
