include::shared/attributes.adoc[]

[[building-apps-for-ios-7]]
= Building Apps for iOS 7

IMPORTANT: iOS 7 has been deprecated in RHMAP.
It is important that a developer avoids deprecated code however, it is still possible to encounter deprecated iOS 7 code in RHMAP due to the ongoing support of Cordova Light.

[[status-bar]]
== Status Bar

From iOS 7, a UI view will use full screen by default which means the status bar will cover the top part of the application. Depending the application's user interface, it may become a problem when running on iOS 7. To help developers deal with this issue, we added a new configuration option in the App Studio called _Old Style Status Bar_ (iOS destinations only). When this option is checked, we will make sure the app uses the old style status bar as seen on iOS 6 devices and it won't overlap with the application. It won't change anything if the app is running on pre iOS 7 devices.

This is done by using a Cordova plugin called https://github.com/apache/cordova-plugin-statusbar[Statusbar^]. It also provides some APIs to allow developers to change the style and behavior of the status bar programmatically. Check out the link for more details.

[[new-icon-dimensions]]
== New Icon Dimensions

Dimensions of iOS 7 icons have been changed. See the xref:icons-and-splashscreens[Icons and Splashscreens] page for updated icon requirements.

These are the things you need to do to make sure the apps are fully compatible with iOS 7. We also suggest you to have a look at the https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/MobileHIG/index.html#//apple_ref/doc/uid/TP40006556[iOS 7 Human Interface Guidelines^] from Apple and make any other necessary changes.
