include::shared/attributes.adoc[]

[[mbaas-targets-and-environments]]
= MBaaS Targets and Environments

[[mbaas-targets-and-environments-overview]]
== Overview

An MBaaS (Mobile Backend as a Service) is a runtime space for Cloud Apps and Cloud Services. Each MBaaS provides a
Node.js runtime, a NoSQL database, a caching server, and all the link:{CloudAPI}[Cloud APIs].

To support application lifecycle management, there's an additional layer of isolation provided for Cloud Apps and Cloud
Services, called __Environments__. You can configure an environment for every life-cycle stage of your project, such as
__Development__, __Testing__, and __Production__. Cloud Apps, Cloud Services and Forms are always deployed in a particular
Environment, and can be easily promoted from one Environment to another.

One MBaaS can host one or more Environments. For example, you could host Development and Testing environment together on
a single MBaaS, but have a separate MBaaS dedicated for a Production Environment. Even when multiple Environments are
hosted on a single MBaaS they only share system resources but still remain isolated on most levels -- separate Node.js
runtime, database, caching server, and also a separate host name.

[[creating-an-mbaas-target]]
== Creating an MBaaS Target

Navigate to the _Admin > MBaaS Targets_ section.

There are three types of MBaaS targets: __FeedHenry__, _OpenShift 2_ and __OpenShift 3__. Each type requires its own specific configuration as described below.

NOTE: An MBaaS target type cannot be changed after its creation.

[[feedhenry-mbaas-target]]
=== FeedHenry MBaaS Target

* *MBaaS ID:* A unique ID for internal reference.
+
This parameter cannot be changed after the MBaaS target creation and cannot contain any special characters or uppercase letters.
+
* *MBaaS Label:* A custom label used within the Studio.
* *MBaaS URL:* The host name of the MBaaS target.
* *Username:* The user name to be used when logging into the instance.
* *Password:* The password to be used when logging into the instance.
* *Service Key:* A key used to identify the system with the FeedHenry MBaaS.

[[openshift-2-mbaas-target]]
=== OpenShift 2 MBaaS Target

* *MBaaS ID:* A unique ID for internal reference.
+
This parameter cannot be changed after the MBaaS target creation and cannot contain any special characters or uppercase letters.
+
* *MBaaS Label:* A custom label used within the Studio.
* *MBaaS URL:* The host name of the public OpenShift instance (for example `openshift.redhat.com`).
* *Username:* OpenShift 2 user name.
* *Password:* OpenShift 2 password.
* *fh-mbaas Host:* Host name of a running fh-mbaas service.
+
NOTE: If you plan to use Forms in your apps, you need to set the _fh-mbaas Host_ field. This requires a few additional steps to deploy an fh-mbaas service on your OpenShift instance. See link:{MobileDeveloperGuide}#enabling-forms-support-in-openshift-2-targets[Enabling Forms support in OpenShift Targets].

[[openshift-3-mbaas-target]]
=== OpenShift 3 MBaaS Target

* *MBaaS ID:* A unique ID for internal reference.
+
This parameter cannot be changed after the MBaaS target creation and cannot contain any special characters or uppercase letters.
+
* *MBaaS Label:* A custom label used within the Studio.
* *OpenShift Master URL:* URL where the OpenShift Master API is available.
* *Username:* OpenShift 3 user name.
* *Password:* OpenShift 3 password.
* *OpenShift Router DNS:* OpenShift 3 Router wildcard DNS entry, for example `*.local.feedhenry.io`.
* **Automatic MBaaS Installation**: The automatically installed MBaaS is not optimized for resiliency and stability required in production environments. For production use, follow the link:{MBaaSAdministrationAndInstallationGuide}#manual-installation[manual installation steps].
* **MBaaS Service Key**: Value of the `FHMBAAS_KEY` environment variable in the fh-mbaas service.
* *MBaaS URL:* Exposed route where fh-mbaas is running in OpenShift.

After you set up an MBaaS target, you also *must* add at least one Environment. Navigate to the _Admin > Environments_
section to add an Environment.

[[creating-an-environment]]
== Creating an Environment

Navigate to the _Admin > Environments_ section.

First, create a new environment using the _Create Environment_ button. You need to set the following parameters:

* *Environment ID:* A unique ID for internal reference.
+
This parameter cannot be changed after the environment creation and cannot contain any special characters or uppercase letters.
+
* *Environment Label:* A custom label used within the Studio.
* *MBaaS Target:* The MBaaS Target to be used by the Environment. An Environment can only use one MBaaS target.

Cloud Apps, Cloud Services and Forms can now be deployed to this new Environment.
