include::shared/attributes.adoc[]

[[cloud-resources]]
= Cloud Resources

[[cloud-resources-overview]]
== Overview

In the Platform, when an app is staged or deployed, it will be running inside a container, also known as a Cloud Environment. Environment resource usage at both the container level and the app level can be managed and viewed here.

.Requirements
The user must be a member of one or more teams with the following permissions:

* Domain -- Cloud Resources (View & Edit)
* Domain -- Projects (View)

.Related Resources
* https://www.npmjs.com/package/fh-fhc[FHC CLI^]
* link:{PlatformAPI}#endpoint-security-api[Platform API - EndPoint Security API]

[[summary-view]]
== Summary View

Once the page is loaded, the resource summary view is presented. You can see what cloud environments are available in your domain and current overall usage of CPU, memory and disk of an environment. Each summary view can be expanded by clicking on it.

[[resources]]
== Resources

You can view the detailed usage of memory, CPU and disk resources in this view. The "Dashboard" view contains an overall view of all three resources and each resource's tab contains both the environment and per-app usage.

[[resources-apps]]
== Apps

You can see all the apps that are currently running inside the environment, see their status, resource usages and manage them as well. Note you will be able to control embed apps (deployed through the build embed app wizard) here as well.

[[cache]]
== Cache

You can see the current cache usage of the environment, flush the cache and reset maximum cache size.
