[[core-persistent-storage-setup]]
= Persistent Storage Setup

[NOTE]
--
Ensure that any NFS server and shares that you use are configured according to the
 https://access.redhat.com/documentation/en/openshift-container-platform/3.4/single/installation-and-configuration/#install-config-persistent-storage-persistent-storage-nfs[OpenShift
 documentation for configuring NFS PersistentVolumes]. See the link:{TroubleshootingGuide}#troubleshooting-nfs-issues[Troubleshooting NFS Issues] section for more information on configuring NFS.
--

The Core requires a number of persistent volumes to exist before installation. As a minimum, make sure your OpenShift cluster has the following persistent volumes in an `Available` state, with at least the amount of free space listed below:

|===
|Component |Minimum recommended size (Default)

|MongoDB
|25Gi

|Metrics Data Backup
|5Gi

|FH SCM
|25Gi

|GitLab Shell
|5Gi

|MySQL
|5Gi

|Nagios
|1Gi
|===

To change the default storage requirements of a component:

. Update the persistent volume claims in the Core OpenShift templates as described in the https://access.redhat.com/documentation/en/openshift-enterprise/3.2/paged/architecture/chapter-4-additional-concepts#architecture-additional-concepts-storage[Persistent Volume documentation^].
+
The following example JSON object definition shows how to create a 25GB persistent volume with `ReadWriteMany` access mode:
+
[source, json]
----
{
  "kind": "PersistentVolume",
  "apiVersion": "v1",
  "metadata": {
    "name": "examplePV"
  },
  "spec": {
    "capacity": {
      "storage": "25Gi"
    },
    "accessModes": [
      "ReadWriteMany"
    ],
    "persistentVolumeReclaimPolicy": "Recycle",
    "nfs": {
      "path": "/path/to/examplePV",
      "server": "172.17.0.2"
    }
  }
}
----
+
[NOTE]
--
For more information on the types of Access Modes read the https://access.redhat.com/documentation/en/openshift-enterprise/3.2/paged/architecture/chapter-4-additional-concepts#pv-access-modes[Persistent Volume Access Modes documentation^].
--

. Review the persistent volume reclaim policy as described in the https://access.redhat.com/documentation/en/openshift-enterprise/3.2/paged/architecture/chapter-4-additional-concepts#pv-recycling-policy[Persistent Volume Reclaim Policy documentation^] to decide which policy suits your requirements.
This policy affects how your data is handled if a persistent volume claim is removed.

[[core-persistent-storage-recommendations]]
== Persistent Storage Recommendations
It is recommended by OpenShift to only use `HostPath` storage for single node testing. Instead of `HostPath` storage, use another driver such as `NFS` when installing the Core. For more information on types of persistent volume read the https://access.redhat.com/documentation/en/openshift-enterprise/3.2/paged/architecture/chapter-4-additional-concepts#types-of-persistent-volumes[Types of Persistent Volumes documentation^].

For detailed information on persistent volumes and how to create them, see https://access.redhat.com/documentation/en/openshift-enterprise/3.2/paged/architecture/chapter-4-additional-concepts#architecture-additional-concepts-storage[Persistent Storage^] in the OpenShift Enterprise documentation.
