include::shared/attributes.adoc[]

[[configuring-rhmap-core-to-use-non-wildcard-ssl-routing]]
= Configuring {ProductShortName} Core to Use Non-wildcard SSL Routing

For a standard {ProductShortName} installation, we
recommend using a wild card SSL certificate installed on the OpenShift
router. However, in situations where this is not desirable, {ProductShortName} can be
exposed using a single URL using the following procedure.

[[non-wildcard-prerequisites]]
== Prerequisites

* A running MBaaS, tested with a Cloud App
* A tested public IP address and domain with an attached certificate

[[rhmap-proxy]]
== Provisioning the {ProductShortName} Proxy

{ProductShortName} Proxy is a separate component which routes requests from a
single external host to Cloud Apps and {ProductShortName} Core instances deployed on OpenShift.

For example, when {ProductShortName} Proxy receives a request for
`https://rhmapproxy.internal.com/cloud_app_id/hello`, that request is translated to
`http://cloud_app_id.internal.com/hello`.

The {ProductShortName} Proxy component is bundled within the RHMAP RPM in the form
of an OpenShift template. Provisioning this template creates an
OpenShift route and exposes this service.

Deploy an {ProductShortName} Proxy for each MBaaS project:

. Set the EXTERNAL_HOST environment variable for client side
connectivity
+
After initialization, a Client App calls {ProductShortName} Core to
discover the URL for making API requests. Set the
following environment variable in the `millicore` component to allow
this call to work behind a {ProductShortName} Proxy.
+
....
oc env dc millicore -n rhmap-core EXTERNAL_HOST=https://<rhmaprouter_internal_domain>
....
+
NOTE: The `EXTERNAL_HOST` environment variable represents the URL which
is exposed to the Internet and is used to retrieve the API URL on application
startup.

. Configure an MBaaS to use an {ProductShortName} Proxy
+
When creating an MBaaS target, specify an external URL using the
`External MBaaS Host` form field. This value is the entry point for
all platform applications.
+
NOTE: For convenience, if the environment variable from step 1. has been
set, this field will be auto-populated with that value.
+
. Deploy the {ProductShortName} Proxy
+
The application takes a number of parameters which should be set in
relation to your infrastructure:

  . BASE_HOST - A *required* parameter which should be set to the domain
name of the OpenShift router. This value should match the cluster
variable
https://docs.openshift.com/container-platform/latest/install_config/install/advanced_install.html#configuring-cluster-variables[openshift_master_cluster_hostname]
  . PLATFORM_URL - An optional parameter which sets the full URL to
RHMAP Core Platform. Example `https://rhmap.internal.domain.com`. In the
case of a single OpenShift infrastructure, this should be set and the
value obtained by running the command
`oc get route rhmap -n rhmap-core -o=yaml | grep host`
  . EXTERNAL_ROUTE - An optional parameter which specifies explicitly
the route that should be created by OpenShift to expose this component.
If not provided, this will be auto generated by OpenShift. This should
match the values provided in steps 1. and 2.
+
To deploy {ProductShortName} Proxy run the following command passing the parameters
described above as appropriate:
+
....
oc new-app -n <myMBaasProjectName> -f /opt/rhmap/templates/core/proxy/fh-nginx-proxy-template.json --param=BASE_HOST=internal.domain.com --param=PLATFORM_URL=https://rhmap.internal.domain.com
....

. Consider the following if you deploy applications behind the RHMAP Proxy
+
If you serve static content from your application, it is important to
consider how paths are written within the applications source code. It
recommended to use relative paths with dot notation.
+
For example where the URL displayed in a browser takes the format
of `https://rhmapproxy.mydomain.com/myAppId/contacts`, in the source
code of that application `<a href=”/contact>Contact us>` should be
written as `<a href=”./contact>Contact us>` as appropriate.
+
Server side applications must have a trailing slash appended to the
URL if one does not exist when viewed in a browser.

. Configure existing proxies
+
If there are existing proxies in your infrastructure,
you must configure these appropriately.

* Reverse proxy
+
A reverse proxy which is an entry point to your infrastructure and exposed to the
Internet must be configured to point to the {ProductShortName} Proxy OpenShift
route.
+
* HTTP proxy
+
When using the {ProductShortName} proxy in conjuction with a HTTP proxy, ensure that the wildcard DNS record that your MBaaS is using refers to a routable IP address that the {ProductShortName} proxy can communicate with , that is the {ProductShortName} proxy must be able to communicate with the IP address of the Cloud Apps deployed to your MBaaS.
+ 

. Configure DNS
+
By default, RHMAP Proxy uses the default OpenShift DNS server to
resolve internal domain names. If you use a custom DNS server
within your network, run the following command to specify your DNS server IP address in the {ProductShortName}
Proxy deployment:
+
....
oc env dc nginx-proxy DNS_SERVER=<ip-address>
....
