include::shared/attributes.adoc[]

[[modifying-smtp-server-setup-in-the-core]]
= Modifying SMTP Server Setup in the Core

The platform sends emails for user account activation, password recovery, form submissions, and other events.

This procedure shows how to set up email support in the Core if it hasn't been set up during installation in the _Frontend setup_ step in the xref:installing-the-core[] section, or if you need to modify the SMTP server setup.

== Setting SMTP Environment Variables on millicore

. Edit the `millicore` deployment configuration and modify the environment variables with values for your SMTP server.
+
[source,bash]
----
oc project <core-project-id>
oc edit dc/millicore
----
+
....
...
spec:
  ...
  template:
    ...
    spec:
      containers:
      - env:
        ...
        - name: SMTP_SERVER
          value: localhost
        - name: SMTP_PORT
          value: "25"
        - name: SMTP_AUTH
          value: "false"
        - name: SMTP_TLS
          value: "false"
        - name: SMTP_USERNAME
          value: ${SMTP_USERNAME}
        - name: SMTP_PASSWORD
          value: ${SMTP_PASSWORD}
        ...
....

. Save you changes and close the editor.

After modifying the deployment configuration, a redeploy of the `millicore` pod is triggered automatically. Once the pod is running again, you can verify the changes.

[[verifying-smtp-settings]]
== Verifying SMTP settings

Verify the SMTP server setup by trying the forgotten password procedure:

. Navigate to the URL of the Studio.
. If you're logged in, log out.
. Under the login form, click _Forgot your password?_
. Fill in your email address.
. Click _Reset my Password_.

You should receive an email with instructions for password recovery.

== Troubleshooting

If the password recovery email doesn't arrive, verify the SMTP settings in the running `millicore` pod.

....
oc env pod -l name=millicore --list | grep SMTP
....

It may help to view the `millicore` logs while attempting the password recovery, looking for any errors related to SMTP or email.

....
oc logs -f millicore-<deploy-uuid>
....

If the test email seems to be sent, but fails to arrive, check it hasn't been placed in your spam or junk folder.
