include::shared/attributes.adoc[]

[[setting-up-smtp-for-cloud-app-alerts]]
= Setting Up SMTP for Cloud App Alerts

[[smtp-notifications-overview]]
== Overview

Each Cloud App can automatically send alerts by e-mail when specified events occur, such as when the Cloud App gets deployed, undeployed, or logs an error. See link:{ProductFeatures}#alerts-email-notifications[Alerts & Email Notifications] for more information.

For the {ProductShortName} 4.x MBaaS based on OpenShift 3, the e-mail function is not available immediately after installation. You must configure an SMTP server to enable e-mail support.

[[smtp-notifications-prerequisites]]
== Prerequisites

* An {ProductShortName} 4.x MBaaS running in OpenShift Enterprise 3
* An account on an SMTP server through which notification alerts can be sent
* An email address where alerts should be sent
* A deployed Cloud App

[[configuring-smtp-settings-in-fh-mbaas]]
== Configuring SMTP settings in fh-mbaas

The `FH_EMAIL_SMTP` and `FH_EMAIL_ALERT_FROM` environment variables in the fh-mbaas DeploymentConfig need to be set, using the below commands:

....
oc project <mbaas-project-id>
oc env dc/fh-mbaas FH_EMAIL_SMTP="smtps://username:password@localhost" FH_EMAIL_ALERT_FROM="admin@example.com"
....

After modifying the DeploymentConfig, a redeploy of the fh-mbaas pod should be triggered automatically. Once the pod is running again, you can verify the changes.

[[verifying-smtp-settings]]
== Verifying SMTP settings

. In the Studio, navigate to a deployed Cloud App.
. Go to the _Notifications > Alerts_ section.
. Click _Create An Alert_ .
. In the _Emails_ field, enter your e-mail address.
. Click __Test Emails__.

You should receive an e-mail from the e-mail address set as `FH_EMAIL_ALERT_FROM`.

[[smtp-notifications-troubleshooting]]
== Troubleshooting

If the test email fails to send, verify the SMTP settings in the running fh-mbaas Pod.

....
oc env pod -l name=fh-mbaas --list | grep EMAIL
....

It may help to view the fh-mbaas logs while attempting to send an email, looking for any errors related to SMTP or email.

....
oc logs -f fh-mbaas-<deploy-uuid>
....

Ensure the Cloud App you are using to send a test mail with is running.
If the test email sends OK, but fails to arrive, check it hasn't been placed in your spam or junk folder.
