include::shared/attributes.adoc[]

[[installing-the-mbaas]]
= Installing the MBaaS

Installation of an MBaaS consists of the following key steps:

. Follow the steps in link:{InstallingRHMAP}#preparing-infrastructure-for-installation[Preparing Infrastructure for Installation].
+
The nodes running RHMAP must have RHEL installed, be a part of an OpenShift cluster, and be registered with Red Hat Subscription Manager.

. Follow the xref:provisioning-an-rhmap-4-x-mbaas-in-openshift-3[Provisioning an {ProductShortName} 4.x MBaaS in OpenShift 3] guide.
+
As part of the provisioning process, OpenShift automatically downloads {ProductShortName} container images from the Red Hat Docker registry.

. Adjust system resource usage of MBaaS components.
+
If the MBaaS components are deployed on dedicated nodes in your cluster (separate from Cloud Apps),
we strongly recommend that you adjust the resource limits of MBaaS components to take full advantage of the available system resources.
+
Follow the xref:adjusting-system-resource-usage-of-the-mbaas-and-cloud-apps[Adjusting System Resource Usage of the MBaaS and Cloud Apps] guide for detailed steps.

. Enable additional features.
.. Set up Cloud App alerts.
* xref:setting-up-smtp-for-cloud-app-alerts[Setting Up SMTP for Cloud App Alerts]

.. Set up centralized logging.
* link:{OperationsGuide}#enabling-centralized-logging[Enabling Centralized Logging]

.. Set up monitoring.
* link:{OperationsGuide}#monitoring-rhmap-with-cockpit[Monitoring {ProductShortName} with Cockpit]
* link:{OperationsGuide}#monitoring-rhmap-with-nagios[Monitoring {ProductShortName} with Nagios]
