include::shared/attributes.adoc[]

// TODO: needs review. Uses a lot of sections for what should be an ordered list of steps.
[[restoring-an-mbaas-backup]]
= Restoring an MBaaS Backup

[[restoring-an-mbaas-backup-overview]]
== Overview
You can back up an MBaaS by following the xref:backing-up-an-mbaas[Backing up an MBaaS] procedure. Once you have created the backup, you can restore a MBaaS to the  state at the time of backup.

[[restoring-an-mbaas-backup-requirements]]
== Requirements
* A self-managed MBaaS installation on an OpenShift platform
* The `oc` binary has a logged in user with permission to edit deployment configurations and view persistent volumes.
* A backup of the data for mongodb and Nagios services as described in xref:backing-up-an-mbaas[Backing up an MBaaS] .

[[what-data-is-restored]]
== What Data is Restored
* Mongodb replicaset data
* Nagios historical data


[[restoring-nagios-data]]
== Restoring Nagios Data
1. Locate the Nagios persistent volume claim-name from the Nagios pod:
+
[source,bash]
----
oc describe pod <nagios-pod-name> | grep "ClaimName:"
claimName: <claim-name>
----

2. Determine the volume-name using the claim-name from step 1:
+
[source,bash]
----
oc describe pvc <claim-name> | grep "Volume:"
Volume: <volume-name>
----

3. Using the volume-name, run the following command:
+
[source,bash,numbered]
----
oc describe pv <volume-name>
----
+
The output contains a `Source` section, similar to:
+
[source,bash]
----
Source:
    Type:      	NFS (an NFS mount that lasts the lifetime of a pod)
    Server:    	nfs-server.local
    Path:      	/path/to/nfs/directory
    ReadOnly:  	false
----
+
This information describes where the data for the Nagios persistent volume
is located.

4. Stop the Nagios pod by editing the Nagios deployment config and set `replicas` to
 `0`:
+
[source,bash]
----
oc edit dc nagios
----
+
Change replicas to 0:
+
[source,bash]
----
spec:
  replicas: 0
----

5. Restore the Nagios data by deleting the contents of the pod's current persistent volume, then extract your backed up data into that directory. Ensure that after extraction the `status.dat` and related files are at the root of the persistent volume.


6. Once the restore is complete, start the Nagios pod by editing the Nagios deployment config and set `replicas` to
 `1`:
+
[source,bash]
----
oc edit dc nagios
----
+
Change replicas back to 1:
+
[source,bash]
----
spec:
  replicas: 1
----

[[restoring-mongodb-data]]
== Restoring MongoDB Data

To restore the MongoDB data, the replicaset must be operational. If this is not the case, see the
xref:mongodb-doesnt-respond-after-repeated-installation-of-the-mbaas[MongoDB doesn't respond after repeated installation of the MBaaS]
section of this guide.

Should you encounter isses with MongoDB, see link:{TroubleshootingGuide}#troubleshooting-mongodb-issues[Troubleshooting MongoDB Issues].

1. Locate the primary Mongodb node.
You must restore using the primary member of the Mongodb replicaset, you can
find this by logging into any of the Mongodb nodes via remote shell:
+
[source,bash]
----
oc rsh <mongodb-pod-name>
----
+
Connect to the mongo shell in this pod:
+
[source,bash]
----
mongo admin -u admin -p ${MONGODB_ADMIN_PASSWORD}
----
+
Check the replicaset status:
+
[source,bash]
----
rs.status()
----
+
The node with the status set to `PRIMARY` is the node to use in the following restoration procedure.

2. Upload MongoDB data to the primary pod using
the `oc rsync` command:
+
[source,bash]
----
oc rsync /path/to/backup/directory/ <primary-mongodb-pod>:/tmp/backup
----
+
TIP: rsync copies everything in a directory. To save time put the MongoDB data files into an empty directory before using rsync.

3. Import data into the Mongodb replicaset
using the 'mongorestore' tool from inside the mongodb pod. Log into the pod:
+
[source,bash]
----
oc rsh <mongodb-pod-name>
----
+
Restore the data:
+
[source,bash]
----
mongorestore -u admin -p <mongo-admin-password> --gzip --archive=mongodb-backup.gz
----
+
For more information on this tool, see the  https://docs.mongodb.com/manual/reference/program/mongorestore/[mongorestore documentation].


[[confirming-restoration]]
== Confirming Restoration
Log in to the Studio and ensure that all the projects, environments and MBaaS targets are correctly restored.
