include::shared/attributes.adoc[]

= 4.3.0 Release Notes

== Release Announcement

=== Proxy options

* RHMAP can be configured to use a proxy for outbound Internet access as described in the link:{CoreAdministrationAndInstallationGuide}[Core Administration and Installation Guide].

* For a standard RHMAP installation, we recommend using a wildcard SSL certificate installed on the OpenShift router. However, in situations where this is not desirable, RHMAP can be configured to use non-wildcard SSL routing as described in the link:{CoreAdministrationAndInstallationGuide}#configuring-rhmap-core-to-use-non-wildcard-ssl-routing[Configuring RHMAP Core to Use Non-wildcard SSL Routing] section.

=== iOS 10, Swift 2.3 and Swift 3.0

This release of RHMAP includes full support for Swift 2.3 and Swift 3.0 functionality. Using Swift 2.3 or Swift 3.0 allows you to use Xcode 8 and iOS 10 specific features, such as iMessage app extensions.

However, this new functionality means that Swift 2.2 apps do not build, and must be migrated to use Xcode 8:

*  Using the easy procedure described in link:{ClientSDK}#migrating-to-swift23[Migrating Apps to Swift 2.3].

*  Using the procedure described in link:{ClientSDK}#migrating-to-swift3[Migrating Apps to Swift 3].


=== Android N

This release of {ProductShortName} includes full support for Android N functionality.

=== Cordova

The Build Farm now supports Cordova CLI 6.3.1, and the following Cordova App platform versions:

* cordova-ios ~4.3.0
* cordova-android ~6.1.1


=== Workforce Management

This release of RHMAP WFM includes better support for session management and improved security features.

=== Push Notification Apps

The performance under high load of apps that use the Platform’s built-in push notification server have been improved.


=== RHMAP Templates

To improve the developer experience, the following changes have been implemented relating to templates:

//(FH-2940)

* Each target platform is now associated with a category, so you can now navigate client apps by target platform.

//( FH-2928, FH-2936)
* By default, templates are sorted by popularity, making it easier to find the most used templates 

// (FH-2941 FH-2933 
* Windows Phone 8 projects have been removed. Note that Windows Universal 8.1 and 10 are still supported.

//(FH-2932, FH-2957) (FH-2934, FH-2935)
* Hello World template client apps are now included in the Hello World Project to improve navigation. Instead of searching for individual templates, you choose this project and select the templates that are applicable to your solution.
Note that this project replaces the  Cordova Hello World Project and the iOS and Android Blank projects have been replaced with Hello World projects. 

//( FH-2929 )
* The Aerogear Service & AeroGear Community Push Project have been removed, use the Push Notification Starter Project for all notification projects. 

//(FH-2930, FH-2931, )
* The Stripe and Intercom services have been removed due to lack of usage.

//(FH-2938)
* The Bare Project template has been renamed to the Empty Project template.


== Known Issues

// https://docs.google.com/document/d/1Fxqt2hOPEErN9P-JMOnezEp1JD6dBphMxW8msOOe4eM/edit#
=== Cordova Plugins

If you use the Build Farm to build Cordova apps and use the following plugins, then you must update them as follows:

* `cordova-plugin-inappbrowser` must be upgraded to 1.6.1 or higher

* `com.ionic.keyboard` must be upgraded to 2.2.1 or higher. Also note that this plugin is now named `ionic-plugin-keyboard`.

//RHMAP-13981
=== Studio Unresponsive

Very large files or repos may cause your browser to become unresponsive when accessing the Studio editor.

=== Sorting of Items in Studio 
// RHMAP-10408
The lists for Projects and Environments in the Studio are not sorted based on creation time. There is no workaround for this issue at the moment.
// RHMAP-10408
Studio allows you to sort items, for example, you can view a list of Projects sorted by last update. However, only the current page is sorted, if you click the next page, the sorting is lost. There is no workaround for this issue at the moment.

// RHMAP-5482
=== When deploying a Cloud App using the Studio, the progress bar sometimes hangs on _In progress_ even after the App has been successfully deployed

The progress log bar on deploy screen is still in an _In progress_ rather than _Success_ state.
The deployment history table entry for this deploy is marked as _Complete/Success_, but the progress bar does not reflect this.
When this issue occurs, the App is actually deployed and it is safe for you to ignore the progress bar and continue normally.

//RHMAP-13569
=== WFM Apps 

If you created an app using the WFM template from RHMAP 3.14 or 4.2, you can no longer build that app using the Build Farm. 
To work around this issue, remove the 'hooks' directory from the app directory.

//RAINCATCH-598
=== Editing Items in WFM Demo Portal

WFM includes a demo portal app that allows you create and edit workflows and workorders. However, if you create a workflow or workorder and immediately edit it after creation, your edits might not be saved. To workaround this issue, always navigate to an old workorder or workflow after creating a new workorder or workflow, before attempting to edit or delete the workflow or workorder you just created. 


//RHMAP-13322
=== Form-based Email Notifications

RHMAP includes a feature that allows you to create a form that triggers an email after each submission. One of the email options is to include the app name, however the emails sent from RHMAP do not include the app name. There is no known workaround for this issue at this time.

// RHMAP-13512
=== Error Messages If an MBaaS is Unavailable

If you perform an action that applies to all environments, but one or more environments is associated with an MBaaS that is currently unavailable, you may see messages that are unhelpful. For example, if you delete a form for a project that is associated with an environment MBaaS that is unstable might result in a 401 error. 
To work around this problem, ensure all MBaaS instances are available.

//RHMAP-10903 -similar to 4.2
=== RHMAP 4.x: Pushing from Environment Variables Screen Corrupts Some REDIS Environment Variables
On the Environment Variables screen in the Studio, you can push any environment variables to your OpenShift 3 Cloud App. However, if you do this and Cloud Apps deploy to Openshift 3, the `FH_REDIS_HOST` and `FH_REDIS_PORT` environment variables in the Cloud App DeploymentConfig will be removed.
If you don't intend to use the fh.cache API, or you don't intend to push any custom environment variables from the Studio, this issue does not affect you.

If you encounter this issue, the fh.cache API in the Cloud App will not work.

To workaround this issue:

1. Make a note of the current values of the 2 environment variables, `FH_REDIS_HOST` and `FH_REDIS_PORT` before pushing environment variables to your Cloud App from the Studio. The values can be found in the Environment Variables screen of the Studio.

2. Push your required environment variables to your OpenShift 3 Cloud App.

3. Manually set the values for `FH_REDIS_HOST` and `FH_REDIS_PORT` in the Cloud App DeploymentConfig using the values noted in step 1.

If you have already pushed environment variables to the Cloud App, and the `FH_REDIS_HOST` and `FH_REDIS_PORT` env vars have been removed, it is possible to determine what the values should be:

* The `FH_REDIS_PORT` value is always `6379`.
* The `FH_REDIS_HOST` value starts with `redis-` and has the same suffix as the Cloud App service. For example, if the Cloud App service is `nodejs-1474446716082eh2c`, the `FH_REDIS_HOST` value is `redis-1474446716082eh2c`


== Resolved Issues

* RHMAP-12936	Unable to deploy fh-advanced-webapp-blank-app to OpenShift MBaaS
* RHMAP-12883	Edits in DataBrowser not persisted in MongoDB
* RHMAP-12823	$fh.auth not working as per documentation
* RHMAP-12790	Broken link in 'mobile-developer-guide' for both 3.x and 4.x
* RHMAP-12729	Error: Unable to export Form Submissions into Drag & Drop Apps
* RHMAP-12719	Exception during a sync call should mark records as crashed
* RHMAP-12628	Remove SimplePush notification from Blank Web App template
* RHMAP-12591	MBaaS Openshift Template in 3.16 should be the productized template
* RHMAP-12528	Update Android SDK reference documentation
* RHMAP-12457	Can't export app for IOS
* RHMAP-12444	fh-health-monitor - add info about how to run it and use of optional ports
* RHMAP-12430	DataTables warning on environment variables section
* RHMAP-12426	[Forms]  Bug when section break component is used more than 10 times in an form with pages
* RHMAP-12412	In the 5.3.1. fhc build command section of the RHMAP documentation is missing the environment param
* RHMAP-12374	Insufficient error details when building app and users does not have permission to read credentials
* RHMAP-12370	formField.fieldId no longer populated for submissionComplete
* RHMAP-12363	FHC refers to latest-2 to check latest version
* RHMAP-12349	[fh-ios-swift-sdk] - Push notifications doesn't work with alias
* RHMAP-12334	lifecycle screen not showing client builds
* RHMAP-12329	Field names are "undefined" in notification mail of form submission
* RHMAP-12321	Unable to create connection tag
* RHMAP-12267	Re-registration for UPS does not work with Android SDK 3.1.0
* RHMAP-12264	Android Builds fail if using cordova-plugin-camera 2.3.1
* RHMAP-12263	Mobile Developer Guide - iOS is outdated
* RHMAP-12116	remove hard-coded links to docs from Studio
* RHMAP-11985	Remove outdated docs contents from Product features
* RHMAP-11946	Update iOS build screen to match Cordova Light deprecation
* RHMAP-11823	Unable to use libxmljs module in studio for node 4.4.3
* RHMAP-11682	iOS app building issues due to arch and old Cordova plugins
* RHMAP-11626	More incorrect links from Studio to docs
* RHMAP-11610	User with data browser view permissions is still able to modify data browser
* RHMAP-11544	Forms - "Blank" Dropdown options pass the required validation
* RHMAP-11485	Update fh-forms to fix vulnerable archiver dependency
* RHMAP-11345	Improve mask env variables popup
* RHMAP-11292	Add an 'engine' config to the barcode-reader-service for node 4
* RHMAP-11151	Issues with FHC on Windows 10
* RHMAP-11047	Improve OpenShift API Token handling in MBaaS Targets
* RHMAP-11040	Error 500 from fhc when deleting environments by id
* RHMAP-10984	Issue building iOS template apps in Studio
* RHMAP-8726	Errors from FHC about missing .md files
* RHMAP-7793	Allow use of the oracledb node module in Cloud Apps
* RHMAP-7304	"Finish" button doesn't work after creating Forms Project without cordova light app
* RHMAP-5708	"Projects Using This Form" displaying incorrect data
* RHMAP-3862	fhc admin domains help is not rendered
* RHMAP-3232	When working on a project, user can't see the whole project name
