include::shared/attributes.adoc[]

[[upgrading-to-red-hat-mobile-application-platform-core-4-3]]
= Upgrading the Core Project 4.2.0 to 4.3.0

[[core-upgrade-4-3-overview]]
== Overview

Upgrading your deployment of {ProductName} ({ProductShortName}) from version 4.2.0 to version 4.3.0 involves the following key steps:

* xref:install-templates-version-4.3[Install OpenShift Templates for RHMAP Core Version 4.3].
* xref:core-create-new-config-maps[Create New ConfigMaps]
* xref:add-required-env-vars[Add Required Enviroment Variables].
* xref:rhmap-core-component-version-upgrade[Upgrade RHMAP Core Components to newer versions].


[[install-templates-version-4.3]]
== Install OpenShift Templates for RHMAP Core Version 4.3

You install {ProductShortName} Core using a set of OpenShift templates.
Get the templates by installing the RPM package `rhmap-fh-openshift-templates`:

. Enable the _RHMAP 4.3 RPMs_ repository in RHEL.
+
[source,bash]
----
subscription-manager repos --enable=rhel-7-server-rhmap-4.3-rpms
----

. Install `rhmap-fh-openshift-templates`
+
[source,bash]
----
yum install rhmap-fh-openshift-templates
----

The templates are installed into the `/opt/rhmap/templates/core` directory.


[[core-create-new-config-maps]]
== Create New ConfigMaps

To create the new ConfigMap run the following command:

[source,bash]
----
oc new-app -f /opt/rhmap/templates/core/fh-core-backend.json
----

Errors relating to existing objects can be ignored as these resources already exist from your previous installation of the Core.

[[add-required-env-vars]]
== Add Required Enviroment Variables

Run the following commands to create the required Environment Variables.

[source,bash]
----

oc env dc/nagios RHMAP_ADMIN_EMAIL=$(oc env dc/nagios --list | grep ADMIN_EMAIL | sed -e "s/ADMIN_EMAIL=//") ADMIN_EMAIL-

for i in fh-aaa fh-metrics fh-messaging fh-ngui fh-supercore fh-appstore gitlab-shell; do oc env dc/${i} --from=configmap/node-proxy; done

oc env dc millicore --containers='millicore' EXTERNAL_HOST="" HTTPD_PROXY_PORT="8010" BUILDER_SERVICE_PROTOCOL=https HTTPD_SERVICE_NAME=rhmap-proxy --from=configmap/millicore-proxy

oc env dc ups --from=configmap/ups-proxy

oc env dc fh-appstore MILLICORE_HTTP_HOST=millicore MILLICORE_HTTP_PORT="8080"

oc patch dc memcached --type='json' -p='[{"op": "replace", "path": "/spec/template/spec/containers/0/resources/limits/memory", "value":"500M"}]'
----



[[rhmap-core-component-version-upgrade]]
== Upgrade RHMAP Core Components to newer versions

Execute the following command for each component. Replace `X.Y.Z-nnnn` with the version of the component's image as listed in the https://access.redhat.com/errata/product/316/ver=4.3/rhel---7/x86_64/RHEA-2017:0522-04[RHEA-2017:0522-04 erratum]:

[source,bash]
----
oc patch dc <component> --type='json' -p='[{"op": "replace", "path": "/spec/template/spec/containers/0/image", "value":"rhmap43/<component>:X.Y.Z-nnnn"}]'
----

The appropriate versions of Core components for {ProductShortName} 4.3.0 are listed in the {ProductShortName} 4.3.0 https://access.redhat.com/errata/product/316/ver=4.3/rhel---7/x86_64/RHEA-2017:0522-04[erratum].

The following tables list the RHMAP Core component names and corresponding image names in RHMAP 4.3.0, starting with the monitoring components:

[[monitoring]]
[cols=",",options="header",]
|==================================
|Monitoring Component |Image name
|nagios |rhmap43/nagios
|==================================

Run the command for each component and wait until all of the new Pods are running successfully, then continue with the infrastructure components:

[[infrastucture]]
[cols=",",options="header",]
|==================================
|Infrastucture Component |Image name
|memcached |rhmap43/memcached
|mongodb |rhmap43/mongodb
|mysql |rhmap43/mysql
|redis |rhmap43/redis
|==================================

Run the command for each component and wait until all of the new Pods are running successfully, then continue with the backend components:

[[backend]]
[cols=",",options="header",]
|==================================
|Backend Component |Image name
|fh-aaa |rhmap43/fh-aaa
|fh-messaging |rhmap43/fh-messaging
|fh-metrics |rhmap43/fh-metrics
|fh-supercore |rhmap43/fh-supercore
|gitlab-shell* |rhmap43/gitlab-shell, rhmap43/httpd
|fh-scm |rhmap43/fh-scm
|ups-eap |rhmap43/ups-eap
|==================================


Run the command for each component and wait until all of the new Pods are running successfully, then continue with the frontend components:

[[frontend]]
[cols=",",options="header",]
|==================================
|Frontend Component |Image name
|fh-ngui |rhmap43/fh-ngui
|fh-appstore | rhmap43/fh-appstore
|millicore* | rhmap43/millicore, rhmap43/httpd, rhmap43/fh-sdks
|==================================

[NOTE]
--
To upgrade a component which contains a number of images (labeled with * above), edit the DeploymentConfig by running the following command:

[source,bash]
----
oc edit dc <component>
----

This opens the DeploymentConfig in the systems default editor.
Find the image tags for the relevant containers and update to the new image values.
--