include::shared/attributes.adoc[]

[[upgrading-to-red-hat-mobile-application-platform-mbaas-4-3]]
= Upgrading Each MBaaS Project 4.2.0 to 4.3.0

[[mbass-upgrade-4-3-overview]]
== Overview

Upgrading your deployment of {ProductName} ({ProductShortName}) from version 4.2.0 to version 4.3.0 involves the following key steps:

* xref:mbaas-create-new-config-maps[Create New configMaps].
* xref:add-required-env-vars[Add Required Enviroment Variables].

[NOTE]
--
Complete the steps below for each MBaaS installation.
--

Before proceeding with the upgrade:


* Make sure to link:{MBaaSAdministrationAndInstallationGuide}#backing-up-an-mbaas[back up all persistent volumes].
* Ensure you have administrator permissions for the OpenShift cluster hosting {ProductShortName}.

[NOTE]
--
During the upgrade procedure, the status of pods changes frequently.

To display a continuously updated view of the status of all pods, run the following command in a terminal on the OpenShift master node:
[source,bash]
----
watch -n1 oc get pods
----
--

[NOTE]
--
Complete the Core upgrade before attempting to upgrade the MBaaS.
--

[[mbaas-create-new-config-maps]]
== Create New configMaps

To create a new config map run the following command:

[source,bash]
----
oc new-app -f /opt/rhmap/templates/mbaas/fh-mbaas-template-3node.json
----

Errors relating to existing objects can be ignored as these resources already exist from your previous installation of the MBaaS

[[add-new-required-env-vars]]
== Add Required Environment Variables

Run the following commands to create the required environment variables.

[source,bash]
----
oc env dc/nagios RHMAP_ADMIN_EMAIL=$(oc env dc/nagios --list | grep ADMIN_EMAIL | sed -e "s/ADMIN_EMAIL=//") ADMIN_EMAIL-

for i in fh-aaa fh-metrics fh-messaging fh-ngui fh-supercore fh-appstore gitlab-shell; do oc env dc/${i} --from=configmap/node-proxy; done
----

[[mbaas-component-version-upgrade]]
== Upgrade MBaaS Components to Newer Versions

The following table lists the MBaaS component names for an {ProductShortName} 4.3.0 MBaaS.

[cols=",",options="header",]
|==================================
|MBaaS Component |Image name
|fh-mbaas |rhmap43/fh-mbaas
|fh-messaging |rhmap43/fh-messaging
|fh-metrics |rhmap43/fh-metrics
|fh-statsd |rhmap43/fh-statsd
|==================================

The appropriate versions of MBaaS components for {ProductShortName} 4.3.0 are listed in the {ProductShortName} https://access.redhat.com/errata/product/316/ver=4.3/rhel---7/x86_64/RHEA-2017:0522-04[RHEA-2017:0522-04 erratum].


. For each of these components, execute the following command:
+
[source,bash]
----
oc patch dc fh-mbaas --type='json' -p='[{"op": "replace", "path": "/spec/template/spec/containers/0/image", "value":"rhmap42/fh-mbaas:X.Y.Z-nnnn"}]'
----
+
This guide uses the `fh-mbaas` component as an example, but the steps are equivalent for all other components. Replace `X.Y.Z-nnnn` with the version of the component's image listed in the https://access.redhat.com/errata/product/316/ver=4.3/rhel---7/x86_64/RHEA-2017:0522-04[erratum].
+
. Repeat step 1 for the remaining components `fh-messaging`, `fh-metrics`, and `fh-statsd`.
